name: Basic Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Setup Grafana k6
        uses: grafana/setup-k6-action@v1.1.0


      - name: Run Grafana k6 tests
        uses: grafana/run-k6-action@v1.1.2
        with:
          path: script.js
          flags: --out dashboard=export=test-report.html

      - name: Upload performance test results
        uses: actions/upload-artifact@v4.4.0
        with:
          name: k6-report
          path: index.json
