name: Basic Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.1   
        with:
          filename: ./script.js
          flags: --out json=index.json --summary-export index.html

      - name: Upload performance test results
        uses: actions/upload-artifact@v4.3.1
        with:
          name: k6-report
          path: index.json