name: Basic Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run with xk6-dashboard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build k6 with xk6-dashboard
        run: |
          xk6 build --with github.com/grafana/xk6-dashboard@latest
          mv k6 ./k6-dashboard

      - name: Run k6 test with dashboard output
        run: |
          ./k6-dashboard run --out 'dashboard=export=test-report.html' script.js

      - name: Upload HTML report
        uses: actions/upload-artifact@v4.4.0
        with:
          name: k6-dashboard-report
          path: test-report.html
